require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AssignmentSubmissionsController do

  # This should return the minimal set of attributes required to create a valid
  # AssignmentSubmission. As you add validations to AssignmentSubmission, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AssignmentSubmissionsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all assignment_submissions as @assignment_submissions" do
      assignment_submission = AssignmentSubmission.create! valid_attributes
      get :index, {}, valid_session
      assigns(:assignment_submissions).should eq([assignment_submission])
    end
  end

  describe "GET show" do
    it "assigns the requested assignment_submission as @assignment_submission" do
      assignment_submission = AssignmentSubmission.create! valid_attributes
      get :show, {:id => assignment_submission.to_param}, valid_session
      assigns(:assignment_submission).should eq(assignment_submission)
    end
  end

  describe "GET new" do
    it "assigns a new assignment_submission as @assignment_submission" do
      get :new, {}, valid_session
      assigns(:assignment_submission).should be_a_new(AssignmentSubmission)
    end
  end

  describe "GET edit" do
    it "assigns the requested assignment_submission as @assignment_submission" do
      assignment_submission = AssignmentSubmission.create! valid_attributes
      get :edit, {:id => assignment_submission.to_param}, valid_session
      assigns(:assignment_submission).should eq(assignment_submission)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new AssignmentSubmission" do
        expect {
          post :create, {:assignment_submission => valid_attributes}, valid_session
        }.to change(AssignmentSubmission, :count).by(1)
      end

      it "assigns a newly created assignment_submission as @assignment_submission" do
        post :create, {:assignment_submission => valid_attributes}, valid_session
        assigns(:assignment_submission).should be_a(AssignmentSubmission)
        assigns(:assignment_submission).should be_persisted
      end

      it "redirects to the created assignment_submission" do
        post :create, {:assignment_submission => valid_attributes}, valid_session
        response.should redirect_to(AssignmentSubmission.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved assignment_submission as @assignment_submission" do
        # Trigger the behavior that occurs when invalid params are submitted
        AssignmentSubmission.any_instance.stub(:save).and_return(false)
        post :create, {:assignment_submission => {}}, valid_session
        assigns(:assignment_submission).should be_a_new(AssignmentSubmission)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        AssignmentSubmission.any_instance.stub(:save).and_return(false)
        post :create, {:assignment_submission => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested assignment_submission" do
        assignment_submission = AssignmentSubmission.create! valid_attributes
        # Assuming there are no other assignment_submissions in the database, this
        # specifies that the AssignmentSubmission created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        AssignmentSubmission.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => assignment_submission.to_param, :assignment_submission => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested assignment_submission as @assignment_submission" do
        assignment_submission = AssignmentSubmission.create! valid_attributes
        put :update, {:id => assignment_submission.to_param, :assignment_submission => valid_attributes}, valid_session
        assigns(:assignment_submission).should eq(assignment_submission)
      end

      it "redirects to the assignment_submission" do
        assignment_submission = AssignmentSubmission.create! valid_attributes
        put :update, {:id => assignment_submission.to_param, :assignment_submission => valid_attributes}, valid_session
        response.should redirect_to(assignment_submission)
      end
    end

    describe "with invalid params" do
      it "assigns the assignment_submission as @assignment_submission" do
        assignment_submission = AssignmentSubmission.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AssignmentSubmission.any_instance.stub(:save).and_return(false)
        put :update, {:id => assignment_submission.to_param, :assignment_submission => {}}, valid_session
        assigns(:assignment_submission).should eq(assignment_submission)
      end

      it "re-renders the 'edit' template" do
        assignment_submission = AssignmentSubmission.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AssignmentSubmission.any_instance.stub(:save).and_return(false)
        put :update, {:id => assignment_submission.to_param, :assignment_submission => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested assignment_submission" do
      assignment_submission = AssignmentSubmission.create! valid_attributes
      expect {
        delete :destroy, {:id => assignment_submission.to_param}, valid_session
      }.to change(AssignmentSubmission, :count).by(-1)
    end

    it "redirects to the assignment_submissions list" do
      assignment_submission = AssignmentSubmission.create! valid_attributes
      delete :destroy, {:id => assignment_submission.to_param}, valid_session
      response.should redirect_to(assignment_submissions_url)
    end
  end

end
