require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ChallengeScoresController do

  # This should return the minimal set of attributes required to create a valid
  # ChallengeScore. As you add validations to ChallengeScore, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all challenge_scores as @challenge_scores" do
      challenge_score = ChallengeScore.create! valid_attributes
      get :index
      assigns(:challenge_scores).should eq([challenge_score])
    end
  end

  describe "GET show" do
    it "assigns the requested challenge_score as @challenge_score" do
      challenge_score = ChallengeScore.create! valid_attributes
      get :show, :id => challenge_score.id
      assigns(:challenge_score).should eq(challenge_score)
    end
  end

  describe "GET new" do
    it "assigns a new challenge_score as @challenge_score" do
      get :new
      assigns(:challenge_score).should be_a_new(ChallengeScore)
    end
  end

  describe "GET edit" do
    it "assigns the requested challenge_score as @challenge_score" do
      challenge_score = ChallengeScore.create! valid_attributes
      get :edit, :id => challenge_score.id
      assigns(:challenge_score).should eq(challenge_score)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ChallengeScore" do
        expect {
          post :create, :challenge_score => valid_attributes
        }.to change(ChallengeScore, :count).by(1)
      end

      it "assigns a newly created challenge_score as @challenge_score" do
        post :create, :challenge_score => valid_attributes
        assigns(:challenge_score).should be_a(ChallengeScore)
        assigns(:challenge_score).should be_persisted
      end

      it "redirects to the created challenge_score" do
        post :create, :challenge_score => valid_attributes
        response.should redirect_to(ChallengeScore.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved challenge_score as @challenge_score" do
        # Trigger the behavior that occurs when invalid params are submitted
        ChallengeScore.any_instance.stub(:save).and_return(false)
        post :create, :challenge_score => {}
        assigns(:challenge_score).should be_a_new(ChallengeScore)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ChallengeScore.any_instance.stub(:save).and_return(false)
        post :create, :challenge_score => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested challenge_score" do
        challenge_score = ChallengeScore.create! valid_attributes
        # Assuming there are no other challenge_scores in the database, this
        # specifies that the ChallengeScore created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ChallengeScore.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => challenge_score.id, :challenge_score => {'these' => 'params'}
      end

      it "assigns the requested challenge_score as @challenge_score" do
        challenge_score = ChallengeScore.create! valid_attributes
        put :update, :id => challenge_score.id, :challenge_score => valid_attributes
        assigns(:challenge_score).should eq(challenge_score)
      end

      it "redirects to the challenge_score" do
        challenge_score = ChallengeScore.create! valid_attributes
        put :update, :id => challenge_score.id, :challenge_score => valid_attributes
        response.should redirect_to(challenge_score)
      end
    end

    describe "with invalid params" do
      it "assigns the challenge_score as @challenge_score" do
        challenge_score = ChallengeScore.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ChallengeScore.any_instance.stub(:save).and_return(false)
        put :update, :id => challenge_score.id, :challenge_score => {}
        assigns(:challenge_score).should eq(challenge_score)
      end

      it "re-renders the 'edit' template" do
        challenge_score = ChallengeScore.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ChallengeScore.any_instance.stub(:save).and_return(false)
        put :update, :id => challenge_score.id, :challenge_score => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested challenge_score" do
      challenge_score = ChallengeScore.create! valid_attributes
      expect {
        delete :destroy, :id => challenge_score.id
      }.to change(ChallengeScore, :count).by(-1)
    end

    it "redirects to the challenge_scores list" do
      challenge_score = ChallengeScore.create! valid_attributes
      delete :destroy, :id => challenge_score.id
      response.should redirect_to(challenge_scores_url)
    end
  end

end
