require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe GradesController do

  # This should return the minimal set of attributes required to create a valid
  # Grade. As you add validations to Grade, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all grades as @grades" do
      grade = Grade.create! valid_attributes
      get :index
      assigns(:grades).should eq([grade])
    end
  end

  describe "GET show" do
    it "assigns the requested grade as @grade" do
      grade = Grade.create! valid_attributes
      get :show, :id => grade.id
      assigns(:grade).should eq(grade)
    end
  end

  describe "GET new" do
    it "assigns a new grade as @grade" do
      get :new
      assigns(:grade).should be_a_new(Grade)
    end
  end

  describe "GET edit" do
    it "assigns the requested grade as @grade" do
      grade = Grade.create! valid_attributes
      get :edit, :id => grade.id
      assigns(:grade).should eq(grade)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Grade" do
        expect {
          post :create, :grade => valid_attributes
        }.to change(Grade, :count).by(1)
      end

      it "assigns a newly created grade as @grade" do
        post :create, :grade => valid_attributes
        assigns(:grade).should be_a(Grade)
        assigns(:grade).should be_persisted
      end

      it "redirects to the created grade" do
        post :create, :grade => valid_attributes
        response.should redirect_to(Grade.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved grade as @grade" do
        # Trigger the behavior that occurs when invalid params are submitted
        Grade.any_instance.stub(:save).and_return(false)
        post :create, :grade => {}
        assigns(:grade).should be_a_new(Grade)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Grade.any_instance.stub(:save).and_return(false)
        post :create, :grade => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested grade" do
        grade = Grade.create! valid_attributes
        # Assuming there are no other grades in the database, this
        # specifies that the Grade created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Grade.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => grade.id, :grade => {'these' => 'params'}
      end

      it "assigns the requested grade as @grade" do
        grade = Grade.create! valid_attributes
        put :update, :id => grade.id, :grade => valid_attributes
        assigns(:grade).should eq(grade)
      end

      it "redirects to the grade" do
        grade = Grade.create! valid_attributes
        put :update, :id => grade.id, :grade => valid_attributes
        response.should redirect_to(grade)
      end
    end

    describe "with invalid params" do
      it "assigns the grade as @grade" do
        grade = Grade.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Grade.any_instance.stub(:save).and_return(false)
        put :update, :id => grade.id, :grade => {}
        assigns(:grade).should eq(grade)
      end

      it "re-renders the 'edit' template" do
        grade = Grade.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Grade.any_instance.stub(:save).and_return(false)
        put :update, :id => grade.id, :grade => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested grade" do
      grade = Grade.create! valid_attributes
      expect {
        delete :destroy, :id => grade.id
      }.to change(Grade, :count).by(-1)
    end

    it "redirects to the grades list" do
      grade = Grade.create! valid_attributes
      delete :destroy, :id => grade.id
      response.should redirect_to(grades_url)
    end
  end

end
