require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe GradeSchemesController do

  # This should return the minimal set of attributes required to create a valid
  # GradeScheme. As you add validations to GradeScheme, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all grade_schemes as @grade_schemes" do
      grade_scheme = GradeScheme.create! valid_attributes
      get :index
      assigns(:grade_schemes).should eq([grade_scheme])
    end
  end

  describe "GET show" do
    it "assigns the requested grade_scheme as @grade_scheme" do
      grade_scheme = GradeScheme.create! valid_attributes
      get :show, :id => grade_scheme.id
      assigns(:grade_scheme).should eq(grade_scheme)
    end
  end

  describe "GET new" do
    it "assigns a new grade_scheme as @grade_scheme" do
      get :new
      assigns(:grade_scheme).should be_a_new(GradeScheme)
    end
  end

  describe "GET edit" do
    it "assigns the requested grade_scheme as @grade_scheme" do
      grade_scheme = GradeScheme.create! valid_attributes
      get :edit, :id => grade_scheme.id
      assigns(:grade_scheme).should eq(grade_scheme)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new GradeScheme" do
        expect {
          post :create, :grade_scheme => valid_attributes
        }.to change(GradeScheme, :count).by(1)
      end

      it "assigns a newly created grade_scheme as @grade_scheme" do
        post :create, :grade_scheme => valid_attributes
        assigns(:grade_scheme).should be_a(GradeScheme)
        assigns(:grade_scheme).should be_persisted
      end

      it "redirects to the created grade_scheme" do
        post :create, :grade_scheme => valid_attributes
        response.should redirect_to(GradeScheme.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved grade_scheme as @grade_scheme" do
        # Trigger the behavior that occurs when invalid params are submitted
        GradeScheme.any_instance.stub(:save).and_return(false)
        post :create, :grade_scheme => {}
        assigns(:grade_scheme).should be_a_new(GradeScheme)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        GradeScheme.any_instance.stub(:save).and_return(false)
        post :create, :grade_scheme => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested grade_scheme" do
        grade_scheme = GradeScheme.create! valid_attributes
        # Assuming there are no other grade_schemes in the database, this
        # specifies that the GradeScheme created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        GradeScheme.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => grade_scheme.id, :grade_scheme => {'these' => 'params'}
      end

      it "assigns the requested grade_scheme as @grade_scheme" do
        grade_scheme = GradeScheme.create! valid_attributes
        put :update, :id => grade_scheme.id, :grade_scheme => valid_attributes
        assigns(:grade_scheme).should eq(grade_scheme)
      end

      it "redirects to the grade_scheme" do
        grade_scheme = GradeScheme.create! valid_attributes
        put :update, :id => grade_scheme.id, :grade_scheme => valid_attributes
        response.should redirect_to(grade_scheme)
      end
    end

    describe "with invalid params" do
      it "assigns the grade_scheme as @grade_scheme" do
        grade_scheme = GradeScheme.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        GradeScheme.any_instance.stub(:save).and_return(false)
        put :update, :id => grade_scheme.id, :grade_scheme => {}
        assigns(:grade_scheme).should eq(grade_scheme)
      end

      it "re-renders the 'edit' template" do
        grade_scheme = GradeScheme.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        GradeScheme.any_instance.stub(:save).and_return(false)
        put :update, :id => grade_scheme.id, :grade_scheme => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested grade_scheme" do
      grade_scheme = GradeScheme.create! valid_attributes
      expect {
        delete :destroy, :id => grade_scheme.id
      }.to change(GradeScheme, :count).by(-1)
    end

    it "redirects to the grade_schemes list" do
      grade_scheme = GradeScheme.create! valid_attributes
      delete :destroy, :id => grade_scheme.id
      response.should redirect_to(grade_schemes_url)
    end
  end

end
