require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe UserAssignmentTypeWeightsController do

  # This should return the minimal set of attributes required to create a valid
  # UserAssignmentTypeWeight. As you add validations to UserAssignmentTypeWeight, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # UserAssignmentTypeWeightsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all user_assignment_type_weights as @user_assignment_type_weights" do
      user_assignment_type_weight = UserAssignmentTypeWeight.create! valid_attributes
      get :index, {}, valid_session
      assigns(:user_assignment_type_weights).should eq([user_assignment_type_weight])
    end
  end

  describe "GET show" do
    it "assigns the requested user_assignment_type_weight as @user_assignment_type_weight" do
      user_assignment_type_weight = UserAssignmentTypeWeight.create! valid_attributes
      get :show, {:id => user_assignment_type_weight.to_param}, valid_session
      assigns(:user_assignment_type_weight).should eq(user_assignment_type_weight)
    end
  end

  describe "GET new" do
    it "assigns a new user_assignment_type_weight as @user_assignment_type_weight" do
      get :new, {}, valid_session
      assigns(:user_assignment_type_weight).should be_a_new(UserAssignmentTypeWeight)
    end
  end

  describe "GET edit" do
    it "assigns the requested user_assignment_type_weight as @user_assignment_type_weight" do
      user_assignment_type_weight = UserAssignmentTypeWeight.create! valid_attributes
      get :edit, {:id => user_assignment_type_weight.to_param}, valid_session
      assigns(:user_assignment_type_weight).should eq(user_assignment_type_weight)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new UserAssignmentTypeWeight" do
        expect {
          post :create, {:user_assignment_type_weight => valid_attributes}, valid_session
        }.to change(UserAssignmentTypeWeight, :count).by(1)
      end

      it "assigns a newly created user_assignment_type_weight as @user_assignment_type_weight" do
        post :create, {:user_assignment_type_weight => valid_attributes}, valid_session
        assigns(:user_assignment_type_weight).should be_a(UserAssignmentTypeWeight)
        assigns(:user_assignment_type_weight).should be_persisted
      end

      it "redirects to the created user_assignment_type_weight" do
        post :create, {:user_assignment_type_weight => valid_attributes}, valid_session
        response.should redirect_to(UserAssignmentTypeWeight.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved user_assignment_type_weight as @user_assignment_type_weight" do
        # Trigger the behavior that occurs when invalid params are submitted
        UserAssignmentTypeWeight.any_instance.stub(:save).and_return(false)
        post :create, {:user_assignment_type_weight => {}}, valid_session
        assigns(:user_assignment_type_weight).should be_a_new(UserAssignmentTypeWeight)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        UserAssignmentTypeWeight.any_instance.stub(:save).and_return(false)
        post :create, {:user_assignment_type_weight => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested user_assignment_type_weight" do
        user_assignment_type_weight = UserAssignmentTypeWeight.create! valid_attributes
        # Assuming there are no other user_assignment_type_weights in the database, this
        # specifies that the UserAssignmentTypeWeight created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        UserAssignmentTypeWeight.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => user_assignment_type_weight.to_param, :user_assignment_type_weight => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested user_assignment_type_weight as @user_assignment_type_weight" do
        user_assignment_type_weight = UserAssignmentTypeWeight.create! valid_attributes
        put :update, {:id => user_assignment_type_weight.to_param, :user_assignment_type_weight => valid_attributes}, valid_session
        assigns(:user_assignment_type_weight).should eq(user_assignment_type_weight)
      end

      it "redirects to the user_assignment_type_weight" do
        user_assignment_type_weight = UserAssignmentTypeWeight.create! valid_attributes
        put :update, {:id => user_assignment_type_weight.to_param, :user_assignment_type_weight => valid_attributes}, valid_session
        response.should redirect_to(user_assignment_type_weight)
      end
    end

    describe "with invalid params" do
      it "assigns the user_assignment_type_weight as @user_assignment_type_weight" do
        user_assignment_type_weight = UserAssignmentTypeWeight.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        UserAssignmentTypeWeight.any_instance.stub(:save).and_return(false)
        put :update, {:id => user_assignment_type_weight.to_param, :user_assignment_type_weight => {}}, valid_session
        assigns(:user_assignment_type_weight).should eq(user_assignment_type_weight)
      end

      it "re-renders the 'edit' template" do
        user_assignment_type_weight = UserAssignmentTypeWeight.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        UserAssignmentTypeWeight.any_instance.stub(:save).and_return(false)
        put :update, {:id => user_assignment_type_weight.to_param, :user_assignment_type_weight => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested user_assignment_type_weight" do
      user_assignment_type_weight = UserAssignmentTypeWeight.create! valid_attributes
      expect {
        delete :destroy, {:id => user_assignment_type_weight.to_param}, valid_session
      }.to change(UserAssignmentTypeWeight, :count).by(-1)
    end

    it "redirects to the user_assignment_type_weights list" do
      user_assignment_type_weight = UserAssignmentTypeWeight.create! valid_attributes
      delete :destroy, {:id => user_assignment_type_weight.to_param}, valid_session
      response.should redirect_to(user_assignment_type_weights_url)
    end
  end

end
